---
version: 2
sources:
- name: "prophecy.prophecy_db"
  database: "prophecy"
  schema: "prophecy_db"
  tables:
  - name: "sales"
    description: "Sales transaction records capturing customer purchases, shipping\
      \ details, and profitability insights."
    columns:
    - name: "row_id"
      description: "Unique identifier for each row in the sales data."
      dataType:
        type: "Bigint"
    - name: "order_id"
      description: "Unique identifier for each customer order."
      dataType:
        type: "Bigint"
    - name: "order_date"
      description: "Date when the order was placed by the customer; Date is in YYYY-MM-DD\
        \ format."
      dataType:
        type: "Date"
    - name: "ship_date"
      description: "Date when the order was shipped to the customer; Date is in YYYY-MM-DD\
        \ format."
      dataType:
        type: "Date"
    - name: "ship_mode"
      description: "Method of shipping chosen for the order, such as standard or express\
        \ delivery."
      dataType:
        type: "String"
    - name: "customer_id"
      description: "Unique identifier for each customer making a purchase."
      dataType:
        type: "Bigint"
    - name: "product_id"
      description: "Unique identifier for each product sold."
      dataType:
        type: "Bigint"
    - name: "sales"
      description: "Total revenue generated from the sale of products."
      dataType:
        type: "Double"
    - name: "quantity"
      description: "Number of units of the product sold in the transaction."
      dataType:
        type: "Bigint"
    - name: "discount"
      description: "Percentage reduction applied to the product's price during the\
        \ sale."
      dataType:
        type: "Double"
    - name: "profit"
      description: "The financial gain achieved from sales after deducting costs."
      dataType:
        type: "Double"
    type: "table"
  - name: "customer"
    description: "Customer demographic and geographic information, aiding in market\
      \ segmentation and regional analysis."
    columns:
    - name: "customer_id"
      description: "Unique identifier for each customer."
      dataType:
        type: "Bigint"
    - name: "customer_name"
      description: "Full name of the customer."
      dataType:
        type: "String"
    - name: "segment"
      description: "Customer classification based on purchasing behavior or demographics."
      dataType:
        type: "String"
    - name: "country"
      description: "Country where the customer resides."
      dataType:
        type: "String"
    - name: "city"
      description: "City where the customer resides."
      dataType:
        type: "String"
    - name: "state"
      description: "The state where the customer resides."
      dataType:
        type: "String"
    - name: "postal_code"
      description: "The postal code for the customer's address."
      dataType:
        type: "Bigint"
    - name: "region"
      description: "The geographical area or division where the customer is located."
      dataType:
        type: "String"
    type: "table"
  - name: "product"
    columns:
    - name: "product_id"
      dataType:
        type: "Bigint"
    - name: "category"
      dataType:
        type: "String"
    - name: "sub_category"
      dataType:
        type: "String"
    - name: "product_name"
      dataType:
        type: "String"
    type: "table"
  - name: "product_profit_summary"
    description: "Summary of product profitability, highlighting financial performance\
      \ for individual products."
    columns:
    - name: "product_name"
      description: "Name of the product for which profit is being calculated."
      dataType:
        type: "String"
    - name: "profit"
      description: "Net profit generated by the product, which can be positive or\
        \ negative."
      dataType:
        type: "Double"
    type: "table"
