name: Example CI/CD with GitHub actions
on:
push:
branches: ["main"]

env:
DATABRICKS_HOST: ${{ secrets.DATABRICKS_URL }}
DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
# replace with your fabric id:
FABRIC_ID: "33898"

jobs:
build:
runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"
      # Install all python dependencies
      # prophecy-libs not included here because prophecy-build-tool takes care of it by reading each pipeline's setup.py
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install build pytest wheel pytest-html pyspark==3.3.0  prophecy-build-tool
      - name: Run PBT validate
        run: pbt validate --path .
      - name: Run PBT build
        run: pbt build --path .
      - name: Run PBT test
        run: pbt test --path .
      - name: Run PBT deploy
        run: pbt deploy --path . --release-version 1.0 --project-id example_project_id
